// Generated by scripts/build.mjs. Do not edit manually.
export const assets = [
  {
    "key": "ravel_gfm_css",
    "file": "assets/ravel-gfm.css",
    "contentType": "text/css; charset=utf-8",
    "remoteUrl": "https://cdn.jsdelivr.net/npm/gfm-it@0.1.3/assets/ravel-gfm.css"
  },
  {
    "key": "whitey_gfm_css",
    "file": "assets/whitey-gfm.css",
    "contentType": "text/css; charset=utf-8",
    "remoteUrl": "https://cdn.jsdelivr.net/npm/gfm-it@0.1.3/assets/whitey-gfm.css"
  },
  {
    "key": "newsprint_gfm_css",
    "file": "assets/newsprint-gfm.css",
    "contentType": "text/css; charset=utf-8",
    "remoteUrl": "https://cdn.jsdelivr.net/npm/gfm-it@0.1.3/assets/newsprint-gfm.css"
  },
  {
    "key": "github_gfm_css",
    "file": "assets/github-gfm.css",
    "contentType": "text/css; charset=utf-8",
    "remoteUrl": "https://cdn.jsdelivr.net/npm/gfm-it@0.1.3/assets/github-gfm.css"
  },
  {
    "key": "highlight_light_css",
    "file": "assets/highlight-light.css",
    "contentType": "text/css; charset=utf-8",
    "remoteUrl": "https://cdn.jsdelivr.net/npm/gfm-it@0.1.3/assets/highlight-light.css"
  },
  {
    "key": "highlight_dark_css",
    "file": "assets/highlight-dark.css",
    "contentType": "text/css; charset=utf-8",
    "remoteUrl": "https://cdn.jsdelivr.net/npm/gfm-it@0.1.3/assets/highlight-dark.css"
  },
  {
    "key": "highlight_js",
    "file": "assets/highlight-core.js",
    "contentType": "application/javascript; charset=utf-8",
    "remoteUrl": "https://cdn.jsdelivr.net/npm/gfm-it@0.1.3/assets/highlight-core.js"
  },
  {
    "key": "gfm_addons_css",
    "file": "assets/gfm-addons.css",
    "contentType": "text/css; charset=utf-8",
    "remoteUrl": "https://cdn.jsdelivr.net/npm/gfm-it@0.1.3/assets/gfm-addons.css"
  },
  {
    "key": "gfm_addons_js",
    "file": "assets/gfm-addons.js",
    "contentType": "application/javascript; charset=utf-8",
    "remoteUrl": "https://cdn.jsdelivr.net/npm/gfm-it@0.1.3/assets/gfm-addons.js"
  }
];

const assetsByKey = new Map(assets.map((asset) => [asset.key, asset]));

export function getAsset(key) {
  const asset = assetsByKey.get(key);
  if (!asset) {
    throw new Error(`Unknown GFM asset: ${key}`);
  }
  return asset;
}

export function getAssetPath(key) {
  return getAsset(key).file;
}

export function getAssetContentType(key) {
  return getAsset(key).contentType;
}

export function getAssetRemoteUrl(key) {
  return getAsset(key).remoteUrl;
}
