import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { assetDefinitions } from './assets.mjs';

const rootDirectory = dirname(fileURLToPath(new URL('../package.json', import.meta.url)));
const packageJsonPath = join(rootDirectory, 'package.json');
const assetsIndexPath = join(rootDirectory, 'assets.js');
const manifestPath = join(rootDirectory, 'manifest.json');
const embeddedPath = join(rootDirectory, 'embedded.js');

function serializeJson(value) {
  return JSON.stringify(value, null, 2).replaceAll('</script', '<\\/script');
}

function createRemoteUrl(packageName, version, filePath) {
  return `https://cdn.jsdelivr.net/npm/${packageName}@${version}/${filePath}`;
}

function createAssets(packageJson) {
  return assetDefinitions.map((asset) => ({
    ...asset,
    remoteUrl: createRemoteUrl(packageJson.name, packageJson.version, asset.file),
  }));
}

function createAssetsIndexOutput(assets) {
  return [
    '// Generated by scripts/build.mjs. Do not edit manually.',
    `export const assets = ${serializeJson(assets)};`,
    '',
    'const assetsByKey = new Map(assets.map((asset) => [asset.key, asset]));',
    '',
    'export function getAsset(key) {',
    '  const asset = assetsByKey.get(key);',
    '  if (!asset) {',
    '    throw new Error(`Unknown GFM asset: ${key}`);',
    '  }',
    '  return asset;',
    '}',
    '',
    'export function getAssetPath(key) {',
    '  return getAsset(key).file;',
    '}',
    '',
    'export function getAssetContentType(key) {',
    '  return getAsset(key).contentType;',
    '}',
    '',
    'export function getAssetRemoteUrl(key) {',
    '  return getAsset(key).remoteUrl;',
    '}',
    '',
  ].join('\n');
}

function createEmbeddedOutput(embeddedAssets) {
  return [
    '// Generated by scripts/build.mjs. Do not edit manually.',
    `export const embeddedAssets = ${serializeJson(embeddedAssets)};`,
    '',
    'const embeddedAssetsByKey = new Map(embeddedAssets.map((asset) => [asset.key, asset]));',
    '',
    'export function getEmbeddedAsset(key) {',
    '  const asset = embeddedAssetsByKey.get(key);',
    '  if (!asset) {',
    '    throw new Error(`Unknown GFM asset: ${key}`);',
    '  }',
    '  return asset;',
    '}',
    '',
    'export function getEmbeddedAssetContent(key, encoding = "utf8") {',
    '  const asset = getEmbeddedAsset(key);',
    '  const content = Buffer.from(asset.contentBase64, "base64");',
    '  return encoding === null ? content : content.toString(encoding);',
    '}',
    '',
  ].join('\n');
}

const packageJson = JSON.parse(await readFile(packageJsonPath, 'utf8'));
const assets = createAssets(packageJson);
const embeddedAssets = [];

for (const asset of assets) {
  const content = await readFile(join(rootDirectory, asset.file));
  embeddedAssets.push({
    ...asset,
    contentBase64: content.toString('base64'),
  });
}

await writeFile(assetsIndexPath, createAssetsIndexOutput(assets));
await writeFile(manifestPath, `${serializeJson(assets)}\n`);
await writeFile(embeddedPath, createEmbeddedOutput(embeddedAssets));

console.log(`generated ${assetsIndexPath}`);
console.log(`generated ${manifestPath}`);
console.log(`generated ${embeddedPath}`);
